### ISSUE TITLE
bug in takeover process for Elastic Beanstalk

### ISSUE THREAD

**Issue by cleo2525** [domain-protect/domain-protect#227]
There appears to be a bug in the takeover process for Elastic Beanstalk. When creating an Elastic Beanstalk environment, you have the option to either specify your own domain or let Elastic Beanstalk create one for you. 

If you choose to let Elastic Beanstalk auto-create the domain for the environment, you will get something like my-eb-app-env.some-random-string.us-east-1.elasticbeanstalk.com.

When Domain Protect's takeover process runs the Cloudformation stack to attempt to takeover the orphaned Elastic Beanstalk environment, the following error is generated, because the "DomainName" parameter sent to the Cloudformation stack includes the auto-generated subdomain which contains a period. I think this can be resolved by stripping off the subdomain.

> Resource handler returned message: "Value my-eb-app-env.eba-ic56qmpr at 'CNAMEPrefix' failed to satisfy constraint: Member must contain only letters, digits, and the dash character and may not start or end with a dash (Service: ElasticBeanstalk, Status Code: 400)

**Comment by paulschwarzenberger** [comment]
It's not possible to take over an Elastic Beanstalk environment with an auto-generated name, because AWS doesn't allow a name with that format to be selected as a custom domain name (as evidenced by your example error). Domain Protect should ignore dangling subdomains with a CNAME in that format, as they are not vulnerable to takeover.
