### ISSUE TITLE
Support using system configured dns resolvers

### ISSUE THREAD

**Issue by buddyledungarees** [domain-protect/domain-protect#256]
Considering security best practices is to block unknown dns resolvers within corp networks as well as disallow bypassing corp dns name servers, the hardcoding of the google dns resolvers from #155 prevents using this within a lot of corporate environments.

Perhaps supporting an argument to specify dns nameservers would be a nice feature to have?

**Comment by paulschwarzenberger** [comment]
Thanks for raising this issue. From personal experience, I'd recommend not trying to run Domain Protect within a corporate network.

Some of the issues which could arise include:
- filtering of DNS responses and DNS timeouts due to tools such as Cisco Umbrella
- some organisations only allow public DNS resolution from their proxy servers
- split DNS with different responses inside the network compared to outside
- what's being tested isn't the same as what's seen by an external attacker or Bug Bounty researcher

Also of note is that I did quite a bit of experimentation before arriving at the use of Google's DNS servers, I found AWS Route53  and CloudFlare DNS resulted in intermittent false positives.

Having said that, I'd be happy to support an argument to specify DNS nameservers, with the default set to what they are now.

Is that something you'd be interested in doing?
