### ISSUE TITLE
2 DNS records pointing to same Dangling domain

### ISSUE THREAD

**Issue by nirmesika** [domain-protect/domain-protect#283]
Hey, Issue is we have 2 DNS records pointing to the same dangling domain, when the Takeover lambda runs it successfully takes over the bucket with records 1 but it fails for records 2 every run (which creates endless cloudformation stacks and failure in slack messages)
Scenario:
Record 1 is 123.abc.com  IN CNAME 123.s3-website-us-east-1.amazonaws.com
Record 2 is 123.xyz.com IN CNAME 123.s3-website-us-east-1.amazonaws.com

Would much appreciate a solution for this scenario.

**Comment by paulschwarzenberger** [comment]
Hi @nirmesika thanks for using OWASP Domain Protect and for raising this issue.

I'm assuming that these are DNS records pointing directly to S3, rather than to CloudFront with a S3 backend?

Assuming the former, my understanding from the AWS documentation is that the bucket name needs to match the domain name, see 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/RoutingToS3Bucket.html
In this case your records should be:
```
Record 1: 123.abc.com IN CNAME 123.abc.com.s3-website-us-east-1.amazonaws.com
Record 2: 123.xyz.com IN CNAME 123.xyz.com.s3-website-us-east-1.amazonaws.com
```
In this case the S3 bucket names would be different so the takeover issue would not apply.

I therefore suspect that the records you noted in the issue would never actually work, in which case they would essentially be incorrect.

**Comment by nirmesika** [comment]
@paulschwarzenberger Thank you for pointing this out.
